"""Write ACCENT_REVIEW.md: every accent-pack rule as a checklist for a native speaker (like LEXICON_REVIEW.md). Run from the repo root:
    python engine/tools/make_accent_review.py
"""

from pathlib import Path

from steve_engine.decode.accents import PACK_IDS, load_pack

ROOT = Path(__file__).resolve().parents[2]


def build() -> str:
    lines = [
        "# Accent pack review sheet",
        "",
        "_Generated by `engine/tools/make_accent_review.py`: do not edit by hand; edit `engine/steve_engine/decode/accents/*.yaml`._",
        "",
        "Every rule below starts as `verified: false`. A native speaker or phonetician should tick the box if the rule is right (then set "
        "`verified: true` in the YAML) or strike it out. If you are not sure, remove the rule: we would rather miss a swap than invent one.",
        "",
        "Reading a rule: **heard X, probably meant Y** (spelling on typed text; the phones are ARPAbet, used on transcripts). Weight is a prior between 0 and 1.",
        "",
    ]
    for pid in PACK_IDS:
        pack = load_pack(pid)
        lines += [f"## {pack.name} (`{pid}`)", "", "| OK? | Heard | Probably meant | Phones | Weight | Why |", "|---|---|---|---|---:|---|"]
        for s in pack.swaps:
            phones = " -> ".join(s.phones) if s.phones else ""
            lines.append(f"| [ ] | `{s.heard}` | `{s.meant}` | {phones} | {s.weight} | {s.note} |")
        if not pack.swaps:
            lines.append("| | _no rules_ | | | | |")
        lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    (ROOT / "ACCENT_REVIEW.md").write_text(build(), encoding="utf-8", newline="\n")
    print("wrote ACCENT_REVIEW.md")
