"""Generate LEXICON_REVIEW.md: every lexicon entry grouped by language, for native-speaker sign-off.

Usage:  python engine/tools/make_lexicon_review.py
Reviewers: tick the box, or fix the entry in engine/steve_engine/lexicon.yaml and set `verified: true`.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from steve_engine.lexicon import load_lexicon

ROOT = Path(__file__).resolve().parents[2]

MEANING = {
    "number": "number", "number_mult": "multiplier", "unit": "dose unit", "frequency_phrase": "frequency word",
    "timing": "time of day", "duration_unit": "duration unit", "negation": "negation", "action_stop": "'stop'",
    "action_call": "'call / tell'", "action_return": "'come back'", "action_continue": "'continue'",
    "action_avoid": "'do not do'", "travel": "'travel'", "symptom": "symptom", "food_relation": "food / before-after",
    "filler": "filler (ignored)", "currency": "currency", "weekday": "weekday", "month": "month",
}


def main() -> None:
    lex = load_lexicon()
    by_lang = defaultdict(list)
    for e in lex.entries:
        by_lang[e.lang].append(e)
    out = [
        "# Lexicon review sheet",
        "",
        "_Generated by `engine/tools/make_lexicon_review.py` — do not edit by hand; edit `engine/steve_engine/lexicon.yaml`._",
        "",
        "Every non-English entry is **unverified**. Native speakers: please check each line —",
        "(1) is the meaning right? (2) are these spellings something people really type? (3) is anything missing that people say in real life?",
        "Wrong or doubtful words should be removed rather than guessed. Change `verified: false` → `true` per entry in the YAML once checked.",
        "",
        f"Total entries: **{len(lex.entries)}** across **{len(by_lang)}** languages.",
        "",
    ]
    for code, cfg in lex.langs.items():
        entries = by_lang[code]
        status = "verified (plain English)" if cfg.verified else "UNVERIFIED — needs a native speaker"
        out += [f"## {cfg.name} (`{code}`) — {len(entries)} entries — {status}", ""]
        if cfg.suffixes:
            out += [f"Suffixes stripped when matching: {', '.join('`-' + s + '`' for s in cfg.suffixes)}", ""]
        cats: dict[str, list] = defaultdict(list)
        for e in entries:
            cats[e.category].append(e)
        for cat, es in cats.items():
            out += [f"### {MEANING.get(cat, cat)}", "", "| ✓ | word | means | spellings by ear | flags |", "|---|---|---|---|---|"]
            for e in es:
                flags = ", ".join(f for f, on in [("ambiguous", e.ambiguous), ("only before a unit", e.adjacent_only), ("carries its own 'not'", e.negates)] if on)
                if e.requires_near:
                    flags = (flags + ", " if flags else "") + "needs nearby: " + "/".join(e.requires_near[:4])
                variants = ", ".join(v for v in e.variants if v != e.canonical)
                val = e.value if not isinstance(e.value, bool) else "yes"
                box = "[x]" if e.verified else "[ ]"
                out.append(f"| {box} | **{e.canonical}** | {val} | {variants} | {flags} |")
            out.append("")
    (ROOT / "LEXICON_REVIEW.md").write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {ROOT / 'LEXICON_REVIEW.md'}")


if __name__ == "__main__":
    main()
