"""Write GLOSSARY_REVIEW.md: every local-phrase glossary entry and every domain word list as a checklist for a native speaker (like ACCENT_REVIEW.md).
Run from the repo root:
    python engine/tools/make_glossary_review.py
"""

from collections import defaultdict
from pathlib import Path

from steve_engine.decode.domain import CATEGORIES, get_domain
from steve_engine.decode.glossary import load_glossary

ROOT = Path(__file__).resolve().parents[2]


def cell(s: str) -> str:
    return s.replace("|", "/").replace("\n", " ")


def build() -> str:
    lines = [
        "# Glossary and word-list review sheet",
        "",
        "_Generated by `engine/tools/make_glossary_review.py`: do not edit by hand; edit `engine/steve_engine/decode/glossary.yaml` and `domain.yaml`._",
        "",
        "Every entry below starts as `verified: false`: the developers wrote them, no native speaker has checked them. Please tick the box if the entry is right "
        "(then set `verified: true` in the YAML), correct it, or strike it out. **If you are not sure, remove it: we would rather explain nothing than explain wrongly.** "
        "Meanings are meant to be neutral and respectful: a phrase is explained, never judged, and a phrase like *inshallah* must not be presented as a lie or an excuse.",
        "",
        "## 1. Local phrases (`glossary.yaml`)",
        "",
        "`Heard as` = other spellings the matcher also accepts. `Plain` = what the plain-English sentence says instead (blank for time and workplace phrases, which are explained but not replaced).",
        "",
    ]
    by_cat: dict[str, list] = defaultdict(list)
    for e in load_glossary():
        by_cat[e.category].append(e)
    for cat in sorted(by_cat):
        lines += [f"### {cat}", "", "| OK? | Phrase | Heard as | Plain | Literal meaning | How it is used | Example |", "|---|---|---|---|---|---|---|"]
        for e in by_cat[cat]:
            plain = cell(e.plain) if e.substitute else ""
            lines.append(f"| [ ] | **{cell(e.phrase)}** | {cell(', '.join(e.variants))} | {plain} | {cell(e.literal)} | {cell(e.social_meaning)} | {cell(e.example)} |")
        lines.append("")
    dom = get_domain()
    lines += [
        "## 2. Word lists the decoder uses to decide what a word is (`domain.yaml`)",
        "",
        "These decide where a place, time, number, amount, action or thing is looked for. A wrong or missing word costs a missed extraction or a needless question. "
        "Please strike anything that is not a normal word for its list and add common ones that are missing.",
        "",
    ]
    for cat in CATEGORIES:
        lines += [f"### {cat}", "", ", ".join(f"`{w}`" for w in sorted(dom.words[cat])), ""]
    return "\n".join(lines)


if __name__ == "__main__":
    (ROOT / "GLOSSARY_REVIEW.md").write_text(build(), encoding="utf-8", newline="\n")
    print("wrote GLOSSARY_REVIEW.md")
