"""Accent packs: sound and spelling substitutions that often turn one English word into another when English is spoken or typed with a
particular mother tongue's sound system (D36, D41). Each pack is a small YAML file in `accents/`; EVERY rule is `verified: false` until a native
speaker has reviewed it (`ACCENT_REVIEW.md`, generated by `engine/tools/make_accent_review.py`). Rules that nobody is sure about are left out.

A swap says: heard `heard`, probably meant `meant` (spelling fragments for typed text) and, when known, the ARPAbet `phones` [heard, meant] for
transcripts. `weight` (0-1) is how much the rule lowers the cost of that sound change when ranking sound-alike words; it is a prior, never a proof.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from functools import cache
from pathlib import Path

import yaml

ACCENT_DIR = Path(__file__).with_name("accents")
PACK_IDS = ("common", "ar", "hi", "ml", "tl")
ARPABET = {"AA", "AE", "AH", "AO", "AW", "AY", "B", "CH", "D", "DH", "EH", "ER", "EY", "F", "G", "HH", "IH", "IY", "JH", "K", "L", "M", "N",
           "NG", "OW", "OY", "P", "R", "S", "SH", "T", "TH", "UH", "UW", "V", "W", "Y", "Z", "ZH"}


@dataclass(frozen=True)
class Swap:
    heard: str
    meant: str
    weight: float
    phones: tuple[str, str] | None
    note: str
    pack: str


@dataclass(frozen=True)
class Pack:
    id: str
    name: str
    swaps: tuple[Swap, ...]
    phrases: tuple[dict, ...]
    verified: bool = False


def _pack(path: Path) -> Pack:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    pid = data["id"]
    if pid != path.stem:
        raise ValueError(f"{path.name}: id {pid!r} does not match the file name")
    if data.get("verified") is not False:
        raise ValueError(f"{path.name}: a pack must be verified: false until a native speaker signs it off")
    swaps = []
    for raw in data.get("swaps", []):
        if raw.get("verified") is not False:
            raise ValueError(f"{path.name}: swap {raw!r} must be verified: false")
        w = float(raw["weight"])
        if not 0 < w <= 1:
            raise ValueError(f"{path.name}: weight {w} must be in (0, 1]")
        heard, meant = str(raw["heard"]).lower(), str(raw["meant"]).lower()
        if not heard.isalpha() or not meant.isalpha() or heard == meant:
            raise ValueError(f"{path.name}: bad swap {heard!r} -> {meant!r}")
        phones = tuple(raw["phones"]) if raw.get("phones") else None
        if phones and (len(phones) != 2 or not set(phones) <= ARPABET):
            raise ValueError(f"{path.name}: phones {phones!r} must be two ARPAbet symbols")
        if not raw.get("note"):
            raise ValueError(f"{path.name}: every swap needs a note saying why")
        swaps.append(Swap(heard, meant, w, phones, raw["note"], pid))
    return Pack(pid, data["name"], tuple(swaps), tuple(data.get("phrases") or ()), False)


@cache
def load_pack(pack_id: str) -> Pack:
    path = ACCENT_DIR / f"{pack_id}.yaml"
    if not path.exists():
        raise KeyError(f"no accent pack {pack_id!r}; available: {', '.join(PACK_IDS)}")
    return _pack(path)


def active_swaps(accent_hint: str | None) -> tuple[Swap, ...]:
    """common + the hinted pack at full weight, and every OTHER pack at half weight (a hint is a guess: people mix, and a sound rule that is right
    for one background is often right for another). With no hint, every pack is at half weight."""
    common = load_pack("common").swaps
    hint = accent_hint.lower() if accent_hint else None
    if hint:
        load_pack(hint)  # unknown pack ids fail loudly
    full = load_pack(hint).swaps if hint else ()
    others = [replace(s, weight=round(s.weight / 2, 3)) for pid in PACK_IDS if pid not in ("common", hint) for s in load_pack(pid).swaps]
    return common + full + tuple(others)
