"""Write docs/API.md, the public contract of the Decode API (D47). Every JSON example in it is produced by calling the real app, so the page cannot drift.

    python scripts/make_api_docs.py            # rewrite docs/API.md
    python scripts/make_api_docs.py --check    # exit 1 if it is stale (also enforced by api/tests/test_api_contract.py)
"""

from __future__ import annotations

import json
import os
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "api"))
os.environ["DATABASE_URL"] = f"sqlite:///{(Path(tempfile.mkdtemp()) / 'docs.db').as_posix()}"
for name in ("SARVAM_API_KEY", "GEMINI_API_KEY", "LLM_ENABLED", "ADMIN_KEY"):
    os.environ[name] = ""

from app.main import app
from app.services import translate as tr
from app.services.decode_sessions import store
from app.settings import settings
from fastapi.testclient import TestClient

KEY = "wk_demoDemoDemoDemoDemoDemoDemo1234"
TEXT = "yalla habibi come to the barking gate tree"
QUESTION = "come to the barking or the building?"


def pj(o) -> str:
    return json.dumps(o, indent=2, ensure_ascii=False)


def call(c: TestClient, method: str, path: str, **kw):
    r = c.request(method, path, **kw)
    return r


def build() -> str:
    tr.service.reset()
    tr.translate_budget.reset()
    store.reset()
    settings.rl_decode_per_min = settings.rl_decode_per_day = settings.decode_per_worker_day = 10_000
    c = TestClient(app, headers={"X-Worker-Key": KEY})
    plain = call(c, "POST", "/decode", json={"text": TEXT, "accent_hint": "ar"}).json()
    q = call(c, "POST", "/decode", json={"text": QUESTION, "accent_hint": "ar"}).json()
    answered = call(c, "POST", "/decode/clarify", json={"decode_id": q["decode_id"], "question_index": 0, "choice": "parking"}).json()
    q2 = call(c, "POST", "/decode", json={"text": QUESTION, "accent_hint": "ar"}).json()
    unsure = call(c, "POST", "/decode/clarify", json={"decode_id": q2["decode_id"], "question_index": 0, "choice": "not_sure"}).json()
    # a translation, produced with the offline FAKE provider: it shows the SHAPE only (the text is not real Malayalam)
    tr.get_providers = lambda language: [tr.FakeTranslator()]
    shape = call(c, "POST", "/decode", json={"text": "come to the parking gate three at five", "reply_language": "ml"}).json()
    tr_only = {k: shape["translation"][k] for k in shape["translation"]}
    voice_off = call(TestClient(app, headers={"X-Worker-Key": KEY}), "POST", "/decode", files={"audio": ("note.wav", b"RIFF", "audio/wav")}).json()
    health = call(TestClient(app), "GET", "/decode/health").json()
    examples = call(TestClient(app), "GET", "/decode/examples").json()
    first = examples["examples"][0]
    e403 = call(TestClient(app), "POST", "/decode", json={"text": "hi"})
    e422 = call(c, "POST", "/decode", json={"text": ""})
    e404 = call(c, "POST", "/decode/clarify", json={"decode_id": "expired-or-unknown", "question_index": 0, "choice": "parking"})
    slim_examples = {"examples": [{"id": e["id"], "label": e["label"], "request": e["request"]} for e in examples["examples"]], "computed_live": True, "each_example_also_has": "response: a full DecodeResponse"}

    text = f"""# Steve Decode API

The public contract of Steve Decode: text or a voice note in, plain English (and optionally the same card in the worker's language) out. **Text only: nothing
in this API speaks or plays audio.** Generated by `scripts/make_api_docs.py` from the running app, so every JSON example below is real output (the machine
translation shape example is the exception, see section 4). The machine-readable contract is [`openapi.json`](../openapi.json) at the repo root; a small typed
TypeScript client is [`clients/ts/steve-client.ts`](../clients/ts/steve-client.ts).

**Stability:** response shapes are stable. A change to any field of `DecodeResponse`, `DecodedCard`, `TranslatedCard`, `DecodeExamples` or `DecodeHealthOut`
needs a decision record in `DECISIONS.md`, a regenerated `openapi.json` and this page (a test fails while they disagree). New optional fields may be added.

## 1. Basics

| | |
|---|---|
| Base URL | wherever the API runs, for example `http://localhost:8000` |
| Format | JSON (`application/json`), or `multipart/form-data` for a voice note |
| Identity | header `X-Worker-Key: wk_<24 to 128 URL-safe characters>` on `POST /decode` and `POST /decode/clarify`. Create one per device in the browser (`crypto.getRandomValues`, base64url) and keep it; the client library does this for you. It is a capability, not a password: only its SHA-256 is used and nothing about the worker is stored. |
| Public (no key) | `GET /decode/health`, `GET /decode/examples`, `GET /health`, `GET /docs` |
| CORS | any origin listed in `CORS_ORIGINS` (comma-separated, or `*`) may call the API from a browser; `CORS_ALLOW_LOCALHOST=false` removes the built-in "any localhost port" rule. Headers `X-Worker-Key` and `Content-Type` are allowed; `Retry-After` is exposed. No cookies are used. |
| Works without keys | yes: typed text always returns an English card. Voice, translation and WhatsApp degrade gracefully (see `notes`). |
| Offsets | every `span` uses Unicode **code points** of the text it points into (`original_text`), not UTF-16 units: slice with `Array.from(text)` in JavaScript. |
| Wording | nothing here says "wrong" or "bad English", and no score is ever shown; `confidence` on the card is internal. |

## 2. Endpoints

### `POST /decode`

Decode a typed or pasted message, **or** a voice note.

**JSON body** `{{ "text": string (1-2000 chars), "accent_hint"?: "ar"|"hi"|"ml"|"tl", "reply_language"?: "en"|"ml"|"hi"|"ur"|"tl"|"bn" }}`

`accent_hint` says which sound patterns to expect from the speaker (Arabic, Hindi/Urdu, Malayalam, Filipino); leave it out when unknown. `reply_language`
asks for the card in that language as well (`en` or missing = English only).

```
curl -X POST http://localhost:8000/decode \\
  -H "Content-Type: application/json" -H "X-Worker-Key: {KEY}" \\
  -d '{{"text": "{TEXT}", "accent_hint": "ar"}}'
```

Response `200` (`DecodeResponse`):

```json
{pj(plain)}
```

**Multipart body** (a voice note): fields `audio` (file: WAV recommended; also mp3, ogg, webm, m4a, flac), optional `accent_hint`, `reply_language`, and optional `text`
(used if the voice note cannot be decoded). At most **4 MB** (413) and, for WAV and Ogg where the length can be read, **30 seconds** (413).

```
curl -X POST http://localhost:8000/decode -H "X-Worker-Key: {KEY}" -F "audio=@note.wav" -F "accent_hint=ar" -F "reply_language=ml"
```

The audio goes to speech-to-text (Sarvam `saaras:v3`, mode `transcribe`, `en-IN`) and the transcript is decoded with the voice-note rules (a transcript is trusted
unless a critical word, a place, time, amount or number, fits its sentence badly). Audio is held in memory for that single call and dropped. `transcript` is
returned. If voice is not available (no key, daily limit, service down, nothing heard) you still get `200`, with `card: null` and a note to show the user, for example:

```json
{pj(voice_off)}
```

### `POST /decode/clarify`

When the decoder is not sure it does **not guess**: `card.clarify` holds a question with options and the response carries a `decode_id`. Send the answer:

`{{ "decode_id": string, "question_index": int, "choice": one of card.clarify[question_index].options, or "not_sure" }}`

Response: the updated `DecodeResponse` (the same shape), with the answer applied and the actions recomputed. Example: a question, then the answer `parking`.

Open question (`POST /decode` with `{QUESTION!r}`, `accent_hint: "ar"`), abridged to the parts that matter:

```json
{pj({"card": {"plain_english": q["card"]["plain_english"], "actions": q["card"]["actions"], "clarify": q["card"]["clarify"]}, "decode_id": q["decode_id"], "say_back": q["say_back"]})}
```

After `POST /decode/clarify` with `{{"decode_id": "...", "question_index": 0, "choice": "parking"}}` (abridged):

```json
{pj({"card": {"plain_english": answered["card"]["plain_english"], "actions": answered["card"]["actions"], "clarify": answered["card"]["clarify"], "changes": [{"heard": ch["heard"], "meant": ch["meant"], "reason": ch["reason"]} for ch in answered["card"]["changes"]]}, "decode_id": answered["decode_id"], "say_back": answered["say_back"]})}
```

With `"choice": "not_sure"` the slot stays empty, the question moves to `card.skipped` and the response has a note and a `say_back` phrase to ask the other person (abridged):

```json
{pj({"card": {"actions": unsure["card"]["actions"], "clarify": unsure["card"]["clarify"], "skipped": [s["question"] for s in unsure["card"]["skipped"]]}, "decode_id": unsure["decode_id"], "notes": unsure["notes"], "say_back": unsure["say_back"]})}
```

State: the original **text** (never audio) and the answers are kept **in memory only**, for `10 minutes` after the last answer, keyed by the worker key. The `decode_id` is
deleted when the last question is answered. An expired, unknown, finished or foreign id all answer `404`. Every answer returns the whole updated card.

### `GET /decode/health`

What works right now, with no secrets. Response `200` (`DecodeHealthOut`):

```json
{pj(health)}
```

`voice` is true only when a speech-to-text key is set and today's voice budget is not used up. `translation.languages` lists, per language, which providers could serve it.

### `GET /decode/examples`

Six ready-made inputs with the cards the engine returns for them **right now** (computed on every request from the live engine, never hard-coded), for demo buttons.
Each item is `{{id, label, request, response}}`: `request` is a valid `POST /decode` body that reproduces the card and lets you continue with `/decode/clarify`;
`response` is a full `DecodeResponse` (with `decode_id: null`). The inputs:

```json
{pj(slim_examples)}
```

The first example, `response.card.actions`, as the engine returns it today:

```json
{pj(first["response"]["card"]["actions"])}
```

## 3. The card (`DecodedCard`)

| Field | Meaning |
|---|---|
| `original_text` | the text that was decoded (the transcript for a voice note) |
| `plain_english` | the message in plain English: sound swaps applied, local phrases replaced, number words as digits |
| `actions.where / when / what / how_much` | `null` or `{{value, evidence}}`. `value` is a short lower-case phrase (`"parking gate 3"`, `"5 pm"`, `"don't come"`, `"50 dirhams"`); `evidence` is the `span` in `original_text`. A negation is always kept in `what`. A slot with an open question is `null`. |
| `changes[]` | words the decoder read differently: `{{span, heard, meant, reason, confidence, source}}` (`source`: `sound`, `phrase`, `context`). `reason` is a full sentence with the accent note when there is one. |
| `phrases[]` | local phrases explained: `{{span, phrase, literal, social_meaning, category}}` (yalla, khalas, inshallah, Maghrib, "kindly revert" ...). All meanings are draft text until a native speaker reviews them. |
| `clarify[]` | open questions: `{{span, options[], question, slot}}`. The decoder asks instead of guessing when two readings are close, and it never silently rewrites a negation, a number, an amount or a named time. |
| `skipped[]` | questions the worker answered with `not_sure` |
| `tips[]` | at most one short, neutral note on the sound pattern ("It often sounds like this: ...") |
| `confidence` | internal number 0 to 1; **never show it as a score** |
| `accent_used`, `path` | the hint that was used; `typed` or `voice` |

`DecodeResponse` = `{{card, translation, transcript, decode_id, notes[], say_back[]}}`. `notes` are human-readable fallbacks to show as they are. `say_back` are short, plain English
phrases the worker can **show** (as text) to the other person, such as "Sorry, parking or barking?". Steve never speaks them.

## 4. Translation (`translation`, optional)

When `reply_language` is `ml`, `hi`, `ur`, `tl` or `bn`, the settled English card is also returned in that language, **as text**. Only the decoded card is translated
(never `original_text`). Numbers, clock times, amounts and currency, the place phrase and the options of a question are protected: a deterministic check requires every
number in the English card to appear unchanged in the translation. **If the check fails, or no provider is available, `translation` is `null`, the English card is
still returned and `notes` says so. A translation that changed a number is never returned.** Not checked: that a negation survived the translation (the checker cannot
read those languages), which is why clients should keep the English card one tap away.

Shape (`TranslatedCard`; produced here with the offline fake provider, so the text is a marker, not real Malayalam):

```json
{pj(tr_only)}
```

`where` and `how_much` are never translated (place names as written on a sign; amount and currency). `provider` is `sarvam` (ml, hi, ur, bn) or `gemini` (tl, and the fallback).

## 5. Errors

Every non-2xx answer is `{{"detail": "<sentence you can show>"}}`.

| Status | When | Example body |
|---|---|---|
| `403` | missing or malformed `X-Worker-Key` | `{json.dumps(e403.json())}` |
| `404` | `/decode/clarify`: expired (10 min without an answer), finished, unknown, or another worker's id | `{json.dumps(e404.json())}` |
| `413` | voice note over 4 MB, over 30 s (WAV, Ogg), or a request over 5 MB | `{{"detail": "That voice note is too large. Please keep it under 30 seconds."}}` |
| `422` | empty or over-long text, unknown `accent_hint` / `reply_language`, neither text nor audio, an unknown `choice` or `question_index` | `{json.dumps(e422.json())}` |
| `429` | rate limit; header `Retry-After: <seconds>` | `{{"detail": "That was a lot of requests in a short time. Please wait 12 seconds and try again."}}` |
| `500` | unexpected error (no internals are leaked) | `{{"detail": "Something went wrong on our side. Please try again in a moment."}}` |

## 6. Limits (environment variables; defaults)

`POST /decode`: 30 per minute and 500 per day per IP (`RL_DECODE_PER_MIN`, `RL_DECODE_PER_DAY`), 200 per day per worker key (`DECODE_PER_WORKER_DAY`).
Voice decodes also count against `STT_DAILY_CAP` (300 per day, all users); translation calls against `TRANSLATE_DAILY_CAP` (300). Audio: `DECODE_MAX_AUDIO_BYTES` (4 MB),
`DECODE_MAX_AUDIO_SECONDS` (30). Clarify state: `CLARIFY_TTL_SECONDS` (600). Every other route: 120 per minute per IP.

## 7. Privacy

Audio and message text are **never stored and never logged**. Audio lives in memory for one speech-to-text call. An open question keeps the original text in memory for 10
minutes (never on disk). Translations are cached in memory for 15 minutes by content hash. Nothing identifies a worker: only the hash of the device key is used, for limits.

## 8. Try it

```
python scripts/export_openapi.py          # regenerate openapi.json
cd api && uvicorn app.main:app --port 8000
curl http://localhost:8000/decode/examples
```

```ts
import {{ SteveClient }} from "./clients/ts/steve-client";
const steve = new SteveClient({{ baseUrl: "http://localhost:8000" }});
const res = await steve.decode({{ text: "{TEXT}", accentHint: "ar" }});
console.log(res.card?.plain_english, res.card?.actions.where?.value);
```
"""
    for real in (q["decode_id"], q2["decode_id"]):
        text = text.replace(real, "kR3x9Q0aV2mZ")  # ids are random per run; the page shows a fixed illustrative one
    return text


if __name__ == "__main__":
    target = ROOT / "docs" / "API.md"
    text = build()
    if "--check" in sys.argv:
        same = target.exists() and target.read_text(encoding="utf-8").replace("\r\n", "\n") == text
        print("docs/API.md is up to date" if same else "docs/API.md is STALE: run python scripts/make_api_docs.py")
        sys.exit(0 if same else 1)
    target.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {target} ({len(text)} bytes)")
